[DEVICE_CONFIG]
Head_TYPE=4096
DEVICE_TYPE=0

;通信配置
[COMM_CONFIG]

;板卡接口类型(1:USB, 2:TCP, 0:USB+TCP)
MB_INTERFACE_TYPE=2

;板卡默认IP
ServerIP=192.168.127.10

;板卡默认TCP端口
ServerPort=5001

;默认通信类型(0:USB, 1:TCP)
DEFAULT_COMM_TYPE=1

;资源配置
[RES_CONFIG]

;HS黑色界面资源
RES_HS_BLACK=resAll\res_HS_Black

;板卡限位配置
[LIMIT_CONFIG]
COUNT=32
0=S_RIGHT
1=S_LEFT
2=S_UP   
3=S_DOWN
4=S_HEADBACK 
;5=S_CWD
;6=S_MARGIN
7=H_MARGIN
8=H_RIGHT
9=H_LEFT
10=S_SAFE(防撞接口)
11=S_MARGIN
;12=S_SIN8
;13=S_SIN9
;14=S_MARGIN
;15=H_MARGIN
;16=H_RIGHT
;17=H_LEFT
;18=H_LY
;19=H_LM
;20=H_LC
;21=H_LK
;22=H_Y
;23=H_M
;24=H_C
;25=H_K
;26=H_SAFE	

;马达、马达限位、限位配置中COUNT值需谨慎修改，不能随意修改接口名称前面的ID序号，如果没有ID序号，可将该项删除或不填

;板卡马达限位配置
[MOTO_LIMIT_CONFIG]
COUNT=16			
0=无限位
1=S_RIGHT_X限位1
2=S_LEFT_X限位2
3=S_UP_升降上限位
4=S_DOWN_升降下限位
5=S_HEADBACK_刮片限位
;6=
;7=S_MARGIN_主板测纸
8=H_MARGIN
9=H_RIGHT
10=H_LEFT
11=S_SAFE(防撞接口)
12=S_MARGIN_主板测纸
;13=
;14=
15=强制限位

;板卡马达配置
[MOTO_CONFIG]
COUNT=8
0=MOTOX_X轴
1=MOTOY_Y轴
;2=J24_X3
;3=J27_X4
;4=X5
;5=X6
;6=J207_升降电机
;7=J208_刮片电机




