[DEVICE_CONFIG]
Head_TYPE=49
DEVICE_TYPE=3

;通信配置
[COMM_CONFIG]

;板卡接口类型(1:USB, 2:TCP, 0:USB+TCP)
MB_INTERFACE_TYPE=2

;板卡默认IP
ServerIP=192.168.127.10

;板卡默认TCP端口
ServerPort=5001

;默认通信类型(0:USB, 1:TCP)
DEFAULT_COMM_TYPE=1

;资源配置
[RES_CONFIG]

;HS黑色界面资源
RES_HS_BLACK=resAll\res_HS_Black

;板卡限位极性配置
[LIMIT_CONFIG]
COUNT=32
0=S_IN1(HOME)
1=S_IN3(END)
2=S_IN6(ECLS0)
3=S_IN8(ECLS1)
4=S_IN4(SINR)
5=S_IN5(CWD)
6=S_IN7(IRST)
;7=S_SIN3
;8=S_SIN4
;9=S_SIN5
;10=S_SIN6
;11=S_RSVD[0]
;12=S_RSVD[1]
;13=S_SIN9
14=S_IN2(PMDS)
15=S_H_MARGIN
16=S_H_RIGHT
17=S_H_LEFT
18=S_H_LY
19=S_H_LM
20=S_H_LC
21=S_H_LK
22=S_H_Y
23=S_H_M
24=S_H_C
25=S_H_K
26=S_H_SAFE	
27=S_H_ORG
28=S_H_END
;马达、马达限位、限位配置中COUNT值需谨慎修改，不能随意修改接口名称前面的ID序号，如果没有ID序号，可将该项删除或不填

;板卡马达限位配置
[MOTO_LIMIT_CONFIG]
COUNT=16			
0=无限位
1=S_IN1(HOME)
2=S_IN3(END)
3=S_IN6(ECLS0)
4=S_IN8(ECLS1)
5=S_IN4(SINR)
6=S_IN5(CWD)
7=S_IN7(IRST)
;8=S_SIN3
;9=S_SIN4
;10=S_SIN5
;11=S_SIN6
10=S_H_ORG
11=S_H_END
12=S_H_RIGHT
13=S_H_LEFT
14=S_IN2(PMDS)
15=强制限位


;板卡马达配置
[MOTO_CONFIG]
COUNT=16
0=J25_X1
1=J26_X2
2=J24_X3
3=J27_X4
;4=X5
;5=X6
;6=X21
;7=X22
8=2J2_HB_Z
;9=HB_Z1
10=ExMOTO1
11=ExMOTO2
12=ExMOTO3
13=ExMOTO4
14=ExMOTO5
15=ExMOTO6



