[DEVICE_CONFIG]
Head_TYPE=12288
DEVICE_TYPE=0

;通信配置
[COMM_CONFIG]

;板卡接口类型(1:USB, 2:TCP, 0:USB+TCP)
MB_INTERFACE_TYPE=1

;板卡默认IP
ServerIP=192.168.127.10

;板卡默认TCP端口
ServerPort=5001

;默认通信类型(0:USB, 1:TCP)
DEFAULT_COMM_TYPE=0

;资源配置
[RES_CONFIG]

;HS黑色界面资源
RES_HS_BLACK=resAll\res_HS_Black

;板卡限位配置
[LIMIT_CONFIG]
COUNT=32
0=S_IN1
1=S_IN0
2=S_IN2
3=S_IN3
4=S_IN5
5=S_IN6
6=S_IN7
;13=S_SIN4
14=S_IN4
15=S_H_MARGIN
16=S_H_RIGHT
17=S_H_LEFT
18=S_H_LY
19=S_H_LM
20=S_H_LC
21=S_H_LK
22=S_H_Y
23=S_H_M
24=S_H_C
25=S_H_K
26=S_H_R0/SAFE0（喷车板安全瓶）
27=S_H_R1/SAFE1（喷车板防撞）

;马达、马达限位、限位配置中COUNT值需谨慎修改，不能随意修改接口名称前面的ID序号，如果没有ID序号，可将该项删除或不填

;板卡马达限位配置
[MOTO_LIMIT_CONFIG]
COUNT=16			
0=无限位
1=S_IN1
2=S_IN0
3=S_IN2
4=S_IN3
5=S_IN5
6=S_IN6
7=S_IN7
14=S_IN4
12=S_H_RIGHT
13=S_H_LEFT
15=强制限位

;板卡马达配置
[MOTO_CONFIG]
COUNT=8
0=J25_X轴
1=J26_Y轴
;2=J24_Z轴
;3=J27_X4
;4=X5
;5=X6
6=X10_升降电机
7=X11_刮片电机



