;资源配置
[RES_CONFIG]

;HS黑色界面资源
RES_HS_BLACK=resAll\res_HS_Black

;HS蓝色界面资源
RES_HS_BLUE=resAll\res_HS_Blue

;HS赛博蓝色界面资源
RES_HS_SAIBO_BLUE=resAll\res_HS_SaiBo_Blue

;HS迈创界面资源
RES_HS_IMAXCAN=resAll\res_HS_IMaxCan

;资源管理
[RES_MANAGER]

;1:表示黑色，2：表示浅蓝色，3：表示赛博蓝,4:表示迈创。其他为默认风格：黑色
SELECT=1