[DEVICE_CONFIG]
Head_TYPE=12288
DEVICE_TYPE=0

;通信配置
[COMM_CONFIG]

;板卡接口类型(1:USB, 2:TCP, 0:USB+TCP)
MB_INTERFACE_TYPE=2

;板卡默认IP
ServerIP=192.168.127.10

;板卡默认TCP端口
ServerPort=5001

;默认通信类型(0:USB, 1:TCP)
DEFAULT_COMM_TYPE=1

;资源配置
[RES_CONFIG]

;HS黑色界面资源
RES_HS_BLACK=resAll\res_HS_Black

;板卡限位配置
[LIMIT_CONFIG]
COUNT=32
0=S_LEFT
1=S_RIGTH`
2=MD_UPDOWN
3=MD_HEADBACK
4=S_H_R0/SAFE0（喷车板安全瓶）
5=S_H_R1/SAFE1（喷车板防撞）
6=S_MARGIN
;7=S_MARGIN
;8=NULL
;9=NULL
;10=NULL
;11=NULL
;12=NULL
;13=NULL
;14=S_MARGIN
15=S_H_MARGIN
16=S_H_RIGHT
17=S_H_LEFT
18=S_H_LY
19=S_H_LM
20=S_H_LC
21=S_H_LK
22=S_H_Y
23=S_H_M
24=S_H_C
25=S_H_K
;26=NULL
;27=NULL
	

;马达、马达限位、限位配置中COUNT值需谨慎修改，不能随意修改接口名称前面的ID序号，如果没有ID序号，可将该项删除或不填

;板卡马达限位配置
[MOTO_LIMIT_CONFIG]
COUNT=16			
0=无限位
1=S_LEFT
2=S_RIGTH
3=S_UPDOWN
4=S_HEADBACK
;5=S_SINR
;6=S_MARGIN
7=S_MARGIN
;8=S_SIN3
;9=S_SIN4
;10=S_SIN5
11=S_H_MARGIN
12=S_H_RIGHT
13=S_H_LEFT
15=强制限位

;板卡马达配置
[MOTO_CONFIG]
COUNT=8
0=MOTO-X/J20
1=MOTO-Y/J21
;2=
;3=
;4=X5
;5=X6
6=MD_J2
7=MD_J7




